// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Hl3zn2iUCFIgDI65ZG_8gNv7D-lODhw',
    appId: '1:474087755126:web:5c3ebef84fe5c39ecbbe57',
    messagingSenderId: '474087755126',
    projectId: 'safe-drive-95876',
    authDomain: 'safe-drive-95876.firebaseapp.com',
    storageBucket: 'safe-drive-95876.firebasestorage.app',
    measurementId: 'G-YFZB1XX07V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSe_-Ihv22CNpOPDSdqaqCFGpr1cLVHk',
    appId: '1:474087755126:android:65d92d63f34b7ed2cbbe57',
    messagingSenderId: '474087755126',
    projectId: 'safe-drive-95876',
    storageBucket: 'safe-drive-95876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-C6VUWct5dgIrcpFQY-tPAztjcX1Y8js',
    appId: '1:474087755126:ios:50d4498f0272be13cbbe57',
    messagingSenderId: '474087755126',
    projectId: 'safe-drive-95876',
    storageBucket: 'safe-drive-95876.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-C6VUWct5dgIrcpFQY-tPAztjcX1Y8js',
    appId: '1:474087755126:ios:50d4498f0272be13cbbe57',
    messagingSenderId: '474087755126',
    projectId: 'safe-drive-95876',
    storageBucket: 'safe-drive-95876.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Hl3zn2iUCFIgDI65ZG_8gNv7D-lODhw',
    appId: '1:474087755126:web:186ae5239cfed2b4cbbe57',
    messagingSenderId: '474087755126',
    projectId: 'safe-drive-95876',
    authDomain: 'safe-drive-95876.firebaseapp.com',
    storageBucket: 'safe-drive-95876.firebasestorage.app',
    measurementId: 'G-X950S2MJKV',
  );
}
